version: "3"

services:

  featureserv:
    image: pramsey/pg_featureserv:latest
    command: "--config /app/config.toml"
    ports:
      - "9000:9000"
    volumes:
      - ./featureserv_config.toml:/app/config.toml:ro
    depends_on:
      postgres:
        condition: service_healthy

  tileserv:
    image: pramsey/pg_tileserv
    command: "--config /app/config.toml"
    ports:
      - "7800:7800"
    volumes:
      - ./tileserv_config.toml:/app/config.toml:ro
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgis/postgis:13-3.2-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:
    driver: local