version: "3"

services:

  featureserv:
    image: pramsey/pg_featureserv:latest
    command: "--config /app/config.toml"
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres/postgres"
    ports:
      - "9000:9000"
    volumes:
      - ./config/pg_featureserv.toml:/app/config.toml:ro
    depends_on:
      postgres:
        condition: service_healthy

  tileserv:
    image: pramsey/pg_tileserv
    command: "--config /app/config.toml"
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres/postgres"
    ports:
      - "7800:7800"
    volumes:
      - ./config/pg_tileserv.toml:/app/config.toml:ro
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgis/postgis:13-3.2-alpine
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - ./web/index.html:/usr/share/nginx/html/index.html:ro
    depends_on:
      - tileserv
      - featureserv


volumes:
  postgres_data:
    driver: local